begin;
select plan(17);
select has_function('graftvision_private','supersede_model_curve',array['uuid','uuid','uuid','text','integer','integer','uuid'],'typed curve supersede exists');
select ok(position('lifecycle_state=''active''' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'only active curve can be superseded');
select ok(position('''tombstone''' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'tombstone version appended');
select ok(position('a.control_points' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'control points preserved');
select ok(position('a.closed' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'closed flag preserved');
select ok(position('a.smoothing_mode' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'smoothing preserved');
select ok(position('supersedes_curve_id' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'prior version is superseded');
select ok(position('current_version_id=v' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'pointer moves to tombstone');
select ok(position('prior_version_id=a.id' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'prior pointer retained');
select ok(position('require_scan_capture_context' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'trusted context required');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'Doctor required');
select ok(position('MODEL_CURVE_POINTER_CONFLICT' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'stale pointer denied');
select ok(position('MODEL_CURVE_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'changed replay denied');
select ok(position('model.annotation_superseded' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'audit action emitted');
select ok(position('storage_key' in pg_get_functiondef('graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))=0,'audit excludes storage paths');
select policies_are('public','model_annotation_curve_version',array[]::name[],'history remains deny-all');
select policies_are('public','model_annotation_curve_current',array[]::name[],'pointers remain deny-all');
select * from finish(); rollback;
