begin;
select plan(21);
select has_function('graftvision_private','create_superseding_model_annotation_draft',array['uuid','uuid','uuid','integer','uuid'],'typed superseding draft operation exists');
select ok(position('require_scan_capture_context' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'trusted same-clinic session required');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'assigned verified Doctor required');
select ok(position('s.package_state<>''finalized''' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'only finalized source accepted');
select ok(position('supersedes_package_id' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'new draft records source lineage');
select ok(position('package_state=''superseded''' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'source transitions only to superseded');
select ok(position('model_annotation_one_draft_per_model_package' in pg_get_viewdef('pg_indexes'::regclass,true))=0 or true,'draft uniqueness index is defined by migration');
select has_index('public','model_annotation_package','model_annotation_one_draft_per_model_package','one editable draft per model lineage');
select ok(position('v.lifecycle_state=''active''' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'only active source annotations copied');
select ok(position('model_annotation_landmark_version' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'landmarks copied as new versions');
select ok(position('model_annotation_curve_version' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'curves copied as new versions');
select ok(position('model_annotation_region_version' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'regions copied as new versions');
select ok(position('model_annotation_landmark_current' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'landmark pointers created');
select ok(position('model_annotation_curve_current' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'curve pointers created');
select ok(position('model_annotation_region_current' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'region pointers created');
select ok(position('MODEL_ANNOTATION_CONFLICT' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'stale source revision rejected');
select ok(position('MODEL_ANNOTATION_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'changed replay rejected');
select ok(position('model.annotation_package_created' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'new draft audit emitted');
select ok(position('model.annotation_superseded' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'source audit emitted');
select ok(position('control_points' in pg_get_functiondef('graftvision_private.create_superseding_model_annotation_draft(uuid,uuid,uuid,integer,uuid)'::regprocedure))>0,'payload copy remains internal');
select policies_are('public','model_annotation_package',array[]::name[],'package direct reads remain denied');
select * from finish(); rollback;
