begin;
select plan(16);
select has_function('graftvision_private','supersede_model_region',array['uuid','uuid','uuid','text','integer','integer','uuid'],'typed region supersede exists');
select ok(position('lifecycle_state=''active''' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'only active region can be superseded');
select ok(position('''tombstone''' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'tombstone version appended');
select ok(position('a.boundary_points' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'boundary points preserved exactly');
select ok(position('a.closed' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'closed-loop state preserved');
select ok(position('supersedes_region_id' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'prior version is superseded');
select ok(position('current_version_id=v' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'pointer moves to tombstone');
select ok(position('prior_version_id=a.id' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'prior pointer retained');
select ok(position('require_scan_capture_context' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'trusted context required');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'Doctor authority required');
select ok(position('MODEL_REGION_POINTER_CONFLICT' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'stale pointer denied');
select ok(position('MODEL_REGION_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'changed replay denied');
select ok(position('model.annotation_superseded' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'redacted audit action emitted');
select ok(position('storage_key' in pg_get_functiondef('graftvision_private.supersede_model_region(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))=0,'audit excludes storage paths');
select policies_are('public','model_annotation_region_version',array[]::name[],'history remains deny-all');
select policies_are('public','model_annotation_region_current',array[]::name[],'pointers remain deny-all');
select * from finish(); rollback;
