begin;
select plan(16);
select has_function('graftvision_private','supersede_model_landmark',array['uuid','uuid','uuid','text','integer','integer','uuid'],'typed landmark supersede exists');
select ok(position('lifecycle_state=''active''' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'only active landmark can be superseded');
select ok(position('''tombstone''' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'tombstone version is appended');
select ok(position('a.normalized_coordinate' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'tombstone retains exact coordinate payload');
select ok(position('supersedes_landmark_id' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'tombstone supersedes active version');
select ok(position('current_version_id=v' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'pointer moves to tombstone');
select ok(position('prior_version_id=a.id' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'prior pointer remains active version');
select ok(position('require_scan_capture_context' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'same clinic trusted context required');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'assigned Doctor required');
select ok(position('MODEL_LANDMARK_POINTER_CONFLICT' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'stale pointer denied');
select ok(position('MODEL_LANDMARK_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'changed idempotency replay denied');
select ok(position('model.annotation_superseded' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))>0,'redacted audit action emitted');
select ok(position('storage_key' in pg_get_functiondef('graftvision_private.supersede_model_landmark(uuid,uuid,uuid,text,integer,integer,uuid)'::regprocedure))=0,'audit excludes storage path');
select policies_are('public','model_annotation_landmark_version',array[]::name[],'historical versions deny direct access');
select policies_are('public','model_annotation_landmark_current',array[]::name[],'pointers deny direct access');
select throws_ok($$insert into public.model_annotation_landmark_current(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,normalization_version,landmark_code,current_version_id,updated_by) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),1,'graftvision-model-normalization-v1','glabella_reference',gen_random_uuid(),gen_random_uuid())$$,null,null,'direct pointer mutation blocked');
select * from finish(); rollback;
