begin;
select plan(25);
select has_function('graftvision_private','save_model_curve',array['uuid','uuid','uuid','text','jsonb','boolean','text','integer','integer','uuid'],'typed curve save exists');
select policies_are('public','model_annotation_curve_version',array[]::name[],'curve versions deny normal users');
select policies_are('public','model_annotation_curve_current',array[]::name[],'curve pointers deny normal users');
select throws_ok($$insert into public.model_annotation_curve_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,curve_code,control_points,revision,created_by) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),1,'current_hairline','[]'::jsonb,1,gen_random_uuid())$$,null,null,'direct curve mutation denied');
select ok(position('crown_boundary' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'closed crown contract present');
select ok(position('n<3' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'open minimum present');
select ok(position('n<4' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'closed minimum present');
select ok(position('n>64' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'maximum present');
select ok(position('order_index' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'contiguous ordering is validated');
select ok(position('count(distinct x->>''id'')' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'duplicate point IDs rejected');
select ok(position('-2 and 2' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'coordinate bounds enforced');
select ok(position('catmull_rom' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'smoothing catalogue enforced');
select ok(position('require_scan_capture_context' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'trusted clinic context required');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'Doctor authority required');
select ok(position('p.package_state<>''draft''' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'finalized package denied');
select ok(position('MODEL_CURVE_POINTER_CONFLICT' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'stale pointer denied');
select ok(position('MODEL_CURVE_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'changed replay denied');
select ok(position('model_annotation_curve_version' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'immutable curve versions appended');
select ok(position('prior_version_id=model_annotation_curve_current.current_version_id' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'prior pointer retained');
select ok(position('model.curve_saved' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'redacted audit action emitted');
select ok(position('storage_key' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))=0,'audit excludes storage path');
select ok(position('control_points' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'points persist only in immutable version');
select ok(position('for update' in lower(pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure)))>0,'row locking present');
select ok(position('p.revision<>p_expected_package_revision' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'stale package denied');
select ok(position('model_annotation_curve_current' in pg_get_functiondef('graftvision_private.save_model_curve(uuid,uuid,uuid,text,jsonb,boolean,text,integer,integer,uuid)'::regprocedure))>0,'current pointer updated');
select * from finish(); rollback;
