begin;
select plan(16);
select col_has_check('public','model_annotation_landmark_version','lifecycle_state','landmark lifecycle is bounded');
select col_has_check('public','model_annotation_curve_version','lifecycle_state','curve lifecycle is bounded');
select col_has_check('public','model_annotation_region_version','lifecycle_state','region lifecycle is bounded');
select col_default_is('public','model_annotation_landmark_version','lifecycle_state','active','existing landmarks default active');
select col_default_is('public','model_annotation_curve_version','lifecycle_state','active','existing curves default active');
select col_default_is('public','model_annotation_region_version','lifecycle_state','active','existing regions default active');
select has_function('graftvision_private','enforce_model_annotation_tombstone',array[]::text[],'tombstone validation function exists');
select has_view('graftvision_private','current_model_annotation_lifecycle','minimal lifecycle discriminator exists');
select ok(position('lifecycle_state<>''active''' in pg_get_functiondef('graftvision_private.enforce_model_annotation_tombstone()'::regprocedure))>0,'tombstone must supersede active evidence');
select ok(position('normalized_coordinate<>new.normalized_coordinate' in pg_get_functiondef('graftvision_private.enforce_model_annotation_tombstone()'::regprocedure))>0,'landmark payload equality required');
select ok(position('control_points<>new.control_points' in pg_get_functiondef('graftvision_private.enforce_model_annotation_tombstone()'::regprocedure))>0,'curve payload equality required');
select ok(position('boundary_points<>new.boundary_points' in pg_get_functiondef('graftvision_private.enforce_model_annotation_tombstone()'::regprocedure))>0,'region payload equality required');
select policies_are('public','model_annotation_landmark_version',array[]::name[],'historical landmarks remain deny-all');
select policies_are('public','model_annotation_curve_version',array[]::name[],'historical curves remain deny-all');
select policies_are('public','model_annotation_region_version',array[]::name[],'historical regions remain deny-all');
select throws_ok($$insert into public.model_annotation_landmark_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,landmark_code,normalized_coordinate,coordinate_frame_version,revision,created_by,lifecycle_state) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),1,'glabella_reference',array[0::numeric,0::numeric,0::numeric],'graftvision-model-normalization-v1',1,gen_random_uuid(),'tombstone')$$,null,null,'direct tombstone mutation is denied');
select * from finish(); rollback;
