begin;
select plan(27);
select has_table('public','reconstruction_prepared_asset','prepared assets are private');
select has_table('public','reconstruction_prepared_manifest','prepared manifest is immutable');
select has_table('public','reconstruction_preparation_event','preparation events are append-only');
select has_table('public','reconstruction_preparation_idempotency','preparation retries are idempotent');
select policies_are('public','reconstruction_prepared_asset',array[]::name[],'direct prepared asset access is denied');
select policies_are('public','reconstruction_prepared_manifest',array[]::name[],'direct prepared manifest access is denied');
select has_function('graftvision_private','read_reconstruction_worker_input',array['uuid','uuid','integer'],'worker input is lease scoped');
select has_function('graftvision_private','record_reconstruction_prepared_asset',array['uuid','uuid','integer','integer','uuid','text','text','text','integer','integer','uuid'],'normalization metadata is controlled');
select has_function('graftvision_private','finalize_reconstruction_prepared_manifest',array['uuid','uuid','integer','integer','uuid'],'prepared manifest finalization is controlled');
select has_function('graftvision_private','read_reconstruction_preparation_status',array['uuid','uuid','uuid'],'safe status is controlled');
select ok(position('require_reconstruction_job_lease' in pg_get_functiondef('graftvision_private.read_reconstruction_worker_input(uuid,uuid,integer)'::regprocedure))>0,'worker read requires current lease');
select ok(position('asset_ids' in pg_get_functiondef('graftvision_private.read_reconstruction_worker_input(uuid,uuid,integer)'::regprocedure))>0,'worker read is bound to manifest assets');
select ok(position('object_key' in pg_get_functiondef('graftvision_private.read_reconstruction_worker_input(uuid,uuid,integer)'::regprocedure))=0,'worker input does not return storage paths');
select ok(position('patient_id' in pg_get_functiondef('graftvision_private.read_reconstruction_worker_input(uuid,uuid,integer)'::regprocedure))=0,'worker input does not return patient identity');
select ok(position('source_checksum' in pg_get_functiondef('graftvision_private.record_reconstruction_prepared_asset(uuid,uuid,integer,integer,uuid,text,text,text,integer,integer,uuid)'::regprocedure))>0,'source checksum is verified');
select ok(position('upload_status=''uploaded''' in pg_get_functiondef('graftvision_private.record_reconstruction_prepared_asset(uuid,uuid,integer,integer,uuid,text,text,text,integer,integer,uuid)'::regprocedure))>0,'superseded assets are denied');
select ok(position('recon-input-prep-v1' in pg_get_functiondef('graftvision_private.record_reconstruction_prepared_asset(uuid,uuid,integer,integer,uuid,text,text,text,integer,integer,uuid)'::regprocedure))>0,'pipeline version is fixed');
select ok(position('cardinality(ids)<>7' in pg_get_functiondef('graftvision_private.finalize_reconstruction_prepared_manifest(uuid,uuid,integer,integer,uuid)'::regprocedure))>0,'seven angles are required');
select ok(position('reconstruction_pending' in pg_get_functiondef('graftvision_private.finalize_reconstruction_prepared_manifest(uuid,uuid,integer,integer,uuid)'::regprocedure))>0,'only preparation boundary progress is reached');
select ok(position('worker_lease_owner' in pg_get_functiondef('graftvision_private.read_reconstruction_preparation_status(uuid,uuid,uuid)'::regprocedure))=0,'safe status excludes worker identity');
select ok(position('normalized_object_reference' in pg_get_functiondef('graftvision_private.read_reconstruction_preparation_status(uuid,uuid,uuid)'::regprocedure))=0,'safe status excludes prepared references');
select ok(position('reconstruction.input_accessed' in pg_get_functiondef('graftvision_private.read_reconstruction_worker_input(uuid,uuid,integer)'::regprocedure))>0,'input access is audited');
select ok(position('reconstruction.asset_normalized' in pg_get_functiondef('graftvision_private.record_reconstruction_prepared_asset(uuid,uuid,integer,integer,uuid,text,text,text,integer,integer,uuid)'::regprocedure))>0,'normalization is audited');
select ok(position('reconstruction.prepared_manifest_created' in pg_get_functiondef('graftvision_private.finalize_reconstruction_prepared_manifest(uuid,uuid,integer,integer,uuid)'::regprocedure))>0,'manifest creation is audited');
select has_trigger('public','reconstruction_prepared_asset','reconstruction_prepared_asset_controlled','direct prepared asset mutation is blocked');
select has_trigger('public','reconstruction_prepared_manifest','reconstruction_prepared_manifest_controlled','direct prepared manifest mutation is blocked');
select has_trigger('public','reconstruction_preparation_event','reconstruction_preparation_event_controlled','direct event mutation is blocked');
select * from finish();
rollback;
