begin;
select plan(25);
select has_table('public', 'scalp_region', 'region root exists');
select has_table('public', 'scalp_region_version', 'region versions exist');
select has_table('public', 'scalp_region_geometry', 'region geometry exists');
select has_function('graftvision_private', 'save_scalp_region', array['uuid','uuid','uuid','uuid','text','text','uuid','integer','text','text','text','jsonb','integer','uuid'], 'controlled region save exists');
select policies_are('public', 'scalp_region', array[]::name[], 'region root denies normal users');
select policies_are('public', 'scalp_region_version', array[]::name[], 'region history denies normal users');
select policies_are('public', 'scalp_region_geometry', array[]::name[], 'region geometry denies normal users');
select col_has_check('public', 'scalp_region', 'region_code', 'taxonomy is bounded');
select col_has_check('public', 'scalp_region_version', 'region_status', 'workflow status is bounded');
select col_has_check('public', 'scalp_region_version', 'source_kind', 'source kind is bounded');
select col_has_check('public', 'scalp_region_version', 'coordinate_frame_version', 'coordinate frame is bounded');
select col_has_check('public', 'scalp_region_version', 'authoring_method', 'authoring method is bounded');
select throws_ok($$insert into public.scalp_region(clinic_id,patient_id,consultation_id,region_code,created_by,updated_by) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'crown_region',gen_random_uuid(),gen_random_uuid())$$, null, null, 'direct region root mutation is blocked');
select throws_ok($$insert into public.scalp_region_version(clinic_id,patient_id,consultation_id,scalp_region_id,region_code,version_number,source_kind,coordinate_frame_version,authoring_method,region_status,created_by) values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),'crown_region',1,'manual','graftvision-manual-relative-v1','manual_draw','draft',gen_random_uuid())$$, null, null, 'direct region version mutation is blocked');
select ok(position('require_active_application_session' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'active session is server-side');
select ok(position('is_assigned_verified_doctor' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'Doctor authority is server-side');
select ok(position('p_region_code not in' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'unknown taxonomy rejected');
select ok(position('p_region_status not in (''draft'', ''review'')' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'approval writes remain outside this infrastructure task');
select ok(position('REGION_REVISION_CONFLICT' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'stale revisions are rejected');
select ok(position('REGION_IDEMPOTENCY_MISMATCH' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'changed replay is rejected');
select ok(position('supersedes_version_id' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'immutable lineage is preserved');
select ok(position('region.version_created' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'audit is emitted');
select ok(position('boundary_points' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'geometry is stored');
select ok(position('jsonb_array_length' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'geometry is bounded');
select ok(position('source_reference_id' in pg_get_functiondef('graftvision_private.save_scalp_region(uuid,uuid,uuid,uuid,text,text,uuid,integer,text,text,text,jsonb,integer,uuid)'::regprocedure)) > 0, 'source lineage is explicit');
select * from finish();
rollback;