-- MODEL-001A: immutable Doctor-viewable technical model packages.
create table public.scalp_model_package (
  id uuid primary key default gen_random_uuid(), clinic_id uuid not null references public.clinic(id), patient_id uuid not null references public.patient(id), consultation_id uuid not null references public.consultation(id), scan_session_id uuid not null references public.scan_session(id), analyzer_handoff_id uuid not null references public.scan_analyzer_handoff(id), reconstruction_job_id uuid not null references public.reconstruction_job(id), reconstruction_output_manifest_id uuid not null references public.reconstruction_output_manifest(id), reconstruction_artifact_id uuid not null references public.reconstruction_artifact(id), artifact_type text not null check (artifact_type in ('mesh_glb','sparse_point_cloud','dense_point_cloud','surface_mesh')), model_mode text not null check (model_mode in ('synthetic_mesh','sparse_point_cloud','dense_point_cloud','surface_mesh')), engine_name text not null check (engine_name in ('recon-engine-synthetic-v1','COLMAP')), engine_version text not null check (engine_version in ('1.0.0','4.1.1')), execution_mode text not null check (execution_mode in ('synthetic','sparse_cpu','dense_cuda')), geometry_revision integer not null check (geometry_revision>0), model_package_version text not null check (model_package_version='graftvision-model-package-v1'), normalization_version text not null check (normalization_version='graftvision-model-normalization-v1'), created_at timestamptz not null default clock_timestamp(), created_by uuid not null, unique(reconstruction_output_manifest_id)
);
alter table public.scalp_model_package enable row level security; alter table public.scalp_model_package force row level security;
revoke all on public.scalp_model_package from public,anon,authenticated;
create trigger scalp_model_package_controlled before insert or update or delete on public.scalp_model_package for each row execute function graftvision_private.enforce_controlled_scan_mutation();
create function graftvision_private.create_scalp_model_package(p_session_id uuid,p_provider_identity_id uuid,p_output_manifest_id uuid,p_idempotency_key uuid) returns table(model_package_id uuid,is_new boolean)
language plpgsql security definer set search_path='' as $$ declare o public.reconstruction_output_manifest%rowtype; a public.reconstruction_artifact%rowtype; c record; p uuid; mode text; begin
 select * into strict o from public.reconstruction_output_manifest where id=p_output_manifest_id; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,o.scan_session_id); if not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,o.consultation_id,'CONSULT-PERM-001') then raise exception using errcode='42501',message='MODEL_ACCESS_DENIED'; end if;
 select * into strict a from public.reconstruction_artifact where id=any(o.artifact_ids) and reconstruction_job_id=o.reconstruction_job_id and attempt_count=o.attempt_count; mode:=case a.artifact_type when 'mesh_glb' then 'synthetic_mesh' else a.artifact_type end;
 select id into p from public.scalp_model_package where reconstruction_output_manifest_id=o.id; if found then return query select p,false; return; end if;
 perform set_config('graftvision.scan_controlled','on',true); insert into public.scalp_model_package(clinic_id,patient_id,consultation_id,scan_session_id,analyzer_handoff_id,reconstruction_job_id,reconstruction_output_manifest_id,reconstruction_artifact_id,artifact_type,model_mode,engine_name,engine_version,execution_mode,geometry_revision,created_by) values(o.clinic_id,o.patient_id,o.consultation_id,o.scan_session_id,o.analyzer_handoff_id,o.reconstruction_job_id,o.id,a.id,a.artifact_type,mode,a.engine_name,a.engine_version,a.execution_mode,o.attempt_count,c.actor_id) returning id into p; return query select p,true; end; $$;
create function graftvision_private.read_scalp_model_package(p_session_id uuid,p_provider_identity_id uuid,p_model_package_id uuid) returns table(model_package_id uuid,model_mode text,artifact_id uuid,engine_name text,engine_version text,execution_mode text,point_count integer,vertex_count integer,face_count integer,bounding_box_mm numeric[],coordinate_system_code text,unit_code text,model_package_version text)
language plpgsql security definer set search_path='' as $$ declare p public.scalp_model_package%rowtype; begin select * into strict p from public.scalp_model_package where id=p_model_package_id; perform graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,p.scan_session_id); if not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,p.consultation_id,'CONSULT-PERM-001') then raise exception using errcode='42501',message='MODEL_ACCESS_DENIED'; end if; return query select p.id,p.model_mode,p.reconstruction_artifact_id,p.engine_name,p.engine_version,p.execution_mode,o.point_count,o.vertex_count,o.face_count,o.bounding_box_mm,o.coordinate_system_code,o.unit_code,p.model_package_version from public.reconstruction_output_manifest o where o.id=p.reconstruction_output_manifest_id; end; $$;
revoke all on function graftvision_private.create_scalp_model_package(uuid,uuid,uuid,uuid),graftvision_private.read_scalp_model_package(uuid,uuid,uuid) from public,anon,authenticated;
