-- MODEL-001B2b2e3: append-only curve tombstone transition.
create function graftvision_private.supersede_model_curve(p_session_id uuid,p_provider_identity_id uuid,p_annotation_package_id uuid,p_curve_code text,p_expected_package_revision integer,p_expected_pointer_revision integer,p_idempotency_key uuid) returns table(tombstone_version_id uuid,package_revision integer,pointer_revision integer,is_new boolean) language plpgsql security definer set search_path='' as $$ declare p public.model_annotation_package%rowtype; m public.scalp_model_package%rowtype; c record; q public.model_annotation_curve_current%rowtype; a public.model_annotation_curve_version%rowtype; e public.model_annotation_idempotency%rowtype; v uuid; h text; begin 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation supersedes.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
select * into strict p from public.model_annotation_package where id=p_annotation_package_id for update; 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation supersedes.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
select * into strict m from public.scalp_model_package where id=p.model_package_id; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,m.scan_session_id); if p.package_state<>'draft' or p.clinic_id<>m.clinic_id or p.patient_id<>m.patient_id or p.consultation_id<>m.consultation_id or p.reconstruction_output_manifest_id<>m.reconstruction_output_manifest_id or p.model_artifact_id<>m.reconstruction_artifact_id or p.geometry_revision<>m.geometry_revision or not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,p.consultation_id,'CONSULT-PERM-001') or p_curve_code not in ('current_hairline','proposed_hairline','frontal_boundary','left_temporal_boundary','right_temporal_boundary','donor_upper_boundary','donor_lower_boundary','donor_left_boundary','donor_right_boundary','crown_boundary') then raise exception using errcode='42501',message='MODEL_CURVE_SUPERSEDE_DENIED'; end if; if p.revision<>p_expected_package_revision then raise exception using errcode='40001',message='MODEL_CURVE_CONFLICT'; end if; h:=encode(extensions.digest(concat_ws(':',p_annotation_package_id,p_curve_code,p_expected_package_revision,p_expected_pointer_revision),'sha256'),'hex'); select * into e from public.model_annotation_idempotency where clinic_id=p.clinic_id and actor_platform_user_id=c.actor_id and request_family='curve' and idempotency_key=p_idempotency_key; if found then if e.payload_hash<>h then raise exception using errcode='40001',message='MODEL_CURVE_IDEMPOTENCY_MISMATCH'; end if; return query select e.result_resource_id,e.result_revision,e.result_revision,false; return; end if; select * into strict q from public.model_annotation_curve_current where annotation_package_id=p.id and curve_code=p_curve_code for update; if q.revision<>p_expected_pointer_revision then raise exception using errcode='40001',message='MODEL_CURVE_POINTER_CONFLICT'; end if; select * into strict a from public.model_annotation_curve_version where id=q.current_version_id and lifecycle_state='active'; perform set_config('graftvision.scan_controlled','on',true); insert into public.model_annotation_curve_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,curve_code,control_points,closed,smoothing_mode,revision,supersedes_curve_id,created_by,lifecycle_state) values(a.annotation_package_id,a.clinic_id,a.patient_id,a.consultation_id,a.model_package_id,a.reconstruction_output_manifest_id,a.model_artifact_id,a.geometry_revision,a.curve_code,a.control_points,a.closed,a.smoothing_mode,p.revision+1,a.id,c.actor_id,'tombstone') returning id into v; 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation supersedes.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
update public.model_annotation_curve_current set current_version_id=v,prior_version_id=a.id,revision=revision+1,updated_at=clock_timestamp(),updated_by=c.actor_id where annotation_package_id=p.id and curve_code=p_curve_code returning revision into pointer_revision; 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation supersedes.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
update public.model_annotation_package set revision=revision+1 where id=p.id returning revision into package_revision; insert into public.model_annotation_event(annotation_package_id,clinic_id,event_type,actor_platform_user_id,annotation_reference_id,annotation_code,revision) values(p.id,p.clinic_id,'superseded',c.actor_id,v,p_curve_code,package_revision); insert into public.audit_event(audit_scope,clinic_id,actor_platform_user_id,actor_type,action,resource_type,resource_id,outcome,request_id,source_application,metadata) values('clinic',p.clinic_id,c.actor_id,'user','model.annotation_superseded','consultation',p.consultation_id,'success',p_idempotency_key,'web',jsonb_build_object('annotation_package_id',p.id,'model_package_id',p.model_package_id,'annotation_kind','curve','annotation_code',p_curve_code,'revision',package_revision,'package_state','draft','geometry_revision',p.geometry_revision)); insert into public.model_annotation_idempotency(clinic_id,actor_platform_user_id,request_family,idempotency_key,payload_hash,result_resource_id,result_status,result_revision) values(p.clinic_id,c.actor_id,'curve',p_idempotency_key,h,v,'created',package_revision); return query select v,package_revision,pointer_revision,true; end; $$;
revoke all on function graftvision_private.supersede_model_curve(uuid,uuid,uuid,text,integer,integer,uuid) from public,anon,authenticated;
