-- MODEL-001B2: controlled, append-only Doctor annotation operations.
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and package revisions serialize immutable Doctor annotation changes.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions and events remain preserved.
create or replace function graftvision_private.require_model_annotation_package(p_session_id uuid,p_provider_identity_id uuid,p_package_id uuid)
returns public.model_annotation_package language plpgsql security definer set search_path='' as $$ declare p public.model_annotation_package%rowtype; m public.scalp_model_package%rowtype; begin
 select * into strict p from public.model_annotation_package where id=p_package_id; select * into strict m from public.scalp_model_package where id=p.model_package_id;
 perform graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,m.scan_session_id);
 if p.clinic_id<>m.clinic_id or p.patient_id<>m.patient_id or p.consultation_id<>m.consultation_id or p.reconstruction_output_manifest_id<>m.reconstruction_output_manifest_id or p.model_artifact_id<>m.reconstruction_artifact_id or p.geometry_revision<>m.geometry_revision or p.package_state<>'draft' or not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,p.consultation_id,'CONSULT-PERM-001') then raise exception using errcode='42501',message='MODEL_ANNOTATION_DENIED'; end if; return p; end; $$;

create function graftvision_private.create_model_annotation_package(p_session_id uuid,p_provider_identity_id uuid,p_model_package_id uuid,p_expected_revision integer,p_idempotency_key uuid) returns table(annotation_package_id uuid,revision integer,is_new boolean)
language plpgsql security definer set search_path='' as $$ declare m public.scalp_model_package%rowtype; c record; p public.model_annotation_package%rowtype; e public.model_annotation_idempotency%rowtype; h text; begin
 select * into strict m from public.scalp_model_package where id=p_model_package_id; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,m.scan_session_id); if not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,m.consultation_id,'CONSULT-PERM-001') then raise exception using errcode='42501',message='MODEL_ANNOTATION_DENIED'; end if;
 h:=encode(extensions.digest(p_model_package_id::text||':'||p_expected_revision::text,'sha256'),'hex'); select * into e from public.model_annotation_idempotency where clinic_id=m.clinic_id and actor_platform_user_id=c.actor_id and request_family='package' and idempotency_key=p_idempotency_key; if found then if e.payload_hash<>h then raise exception using errcode='40001',message='MODEL_ANNOTATION_IDEMPOTENCY_MISMATCH'; end if; return query select e.result_resource_id,e.result_revision,false; return; end if;
 select * into p from public.model_annotation_package where model_package_id=m.id and package_state='draft' order by created_at desc limit 1 for update; if found then return query select p.id,p.revision,false; return; end if;
 perform set_config('graftvision.scan_controlled','on',true); insert into public.model_annotation_package(clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,created_by) values(m.clinic_id,m.patient_id,m.consultation_id,m.id,m.reconstruction_output_manifest_id,m.reconstruction_artifact_id,m.geometry_revision,c.actor_id) returning * into p; insert into public.model_annotation_event(annotation_package_id,clinic_id,event_type,actor_platform_user_id,revision) values(p.id,p.clinic_id,'package_created',c.actor_id,p.revision); insert into public.model_annotation_idempotency(clinic_id,actor_platform_user_id,request_family,idempotency_key,payload_hash,result_resource_id,result_status,result_revision) values(p.clinic_id,c.actor_id,'package',p_idempotency_key,h,p.id,'created',p.revision); return query select p.id,p.revision,true; end; $$;

create function graftvision_private.save_model_annotation(p_session_id uuid,p_provider_identity_id uuid,p_package_id uuid,p_kind text,p_code text,p_payload jsonb,p_expected_revision integer,p_idempotency_key uuid) returns table(annotation_id uuid,revision integer,is_new boolean)
language plpgsql security definer set search_path='' as $$ declare p public.model_annotation_package%rowtype; c record; h text; e public.model_annotation_idempotency%rowtype; v uuid; event_name text; begin
 select * into strict p from graftvision_private.require_model_annotation_package(p_session_id,p_provider_identity_id,p_package_id) for update; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,(select scan_session_id from public.scalp_model_package where id=p.model_package_id)); if p.revision<>p_expected_revision then raise exception using errcode='40001',message='MODEL_ANNOTATION_CONFLICT'; end if; if p_kind not in ('landmark','curve','region') or jsonb_typeof(p_payload)<>'object' then raise exception using errcode='22023',message='MODEL_ANNOTATION_INVALID'; end if; h:=encode(extensions.digest(p_kind||':'||p_code||':'||p_payload::text||':'||p_expected_revision::text,'sha256'),'hex'); select * into e from public.model_annotation_idempotency where clinic_id=p.clinic_id and actor_platform_user_id=c.actor_id and request_family=p_kind and idempotency_key=p_idempotency_key; if found then if e.payload_hash<>h then raise exception using errcode='40001',message='MODEL_ANNOTATION_IDEMPOTENCY_MISMATCH'; end if; return query select e.result_resource_id,e.result_revision,false; return; end if; perform set_config('graftvision.scan_controlled','on',true);
 if p_kind='landmark' then insert into public.model_annotation_landmark_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,landmark_code,normalized_coordinate,surface_reference,coordinate_frame_version,revision,created_by) values(p.id,p.clinic_id,p.patient_id,p.consultation_id,p.model_package_id,p.reconstruction_output_manifest_id,p.model_artifact_id,p.geometry_revision,p_code,array(select jsonb_array_elements_text(p_payload->'coordinate')::numeric),nullif(p_payload->>'surface_reference',''),'graftvision-model-normalization-v1',p.revision+1,c.actor_id) returning id into v; event_name:='landmark_saved'; elsif p_kind='curve' then insert into public.model_annotation_curve_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,curve_code,control_points,closed,smoothing_mode,revision,created_by) values(p.id,p.clinic_id,p.patient_id,p.consultation_id,p.model_package_id,p.reconstruction_output_manifest_id,p.model_artifact_id,p.geometry_revision,p_code,p_payload->'points',coalesce((p_payload->>'closed')::boolean,false),coalesce(p_payload->>'smoothing_mode','linear'),p.revision+1,c.actor_id) returning id into v; event_name:='curve_saved'; else insert into public.model_annotation_region_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,region_code,boundary_points,closed,revision,created_by) values(p.id,p.clinic_id,p.patient_id,p.consultation_id,p.model_package_id,p.reconstruction_output_manifest_id,p.model_artifact_id,p.geometry_revision,p_code,p_payload->'points',true,p.revision+1,c.actor_id) returning id into v; event_name:='region_saved'; end if; update public.model_annotation_package set revision=revision+1 where id=p.id; insert into public.model_annotation_event(annotation_package_id,clinic_id,event_type,actor_platform_user_id,annotation_reference_id,annotation_code,revision) values(p.id,p.clinic_id,event_name,c.actor_id,v,p_code,p.revision+1); insert into public.model_annotation_idempotency(clinic_id,actor_platform_user_id,request_family,idempotency_key,payload_hash,result_resource_id,result_status,result_revision) values(p.clinic_id,c.actor_id,p_kind,p_idempotency_key,h,v,'created',p.revision+1); return query select v,p.revision+1,true; end; $$;

create function graftvision_private.finalize_model_annotation_package(p_session_id uuid,p_provider_identity_id uuid,p_package_id uuid,p_expected_revision integer,p_idempotency_key uuid) returns table(revision integer,is_new boolean) language plpgsql security definer set search_path='' as $$ declare p public.model_annotation_package%rowtype; c record; begin select * into strict p from graftvision_private.require_model_annotation_package(p_session_id,p_provider_identity_id,p_package_id) for update; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,(select scan_session_id from public.scalp_model_package where id=p.model_package_id)); if p.revision<>p_expected_revision then raise exception using errcode='40001',message='MODEL_ANNOTATION_CONFLICT'; end if; perform set_config('graftvision.scan_controlled','on',true); update public.model_annotation_package set package_state='finalized',finalized_at=clock_timestamp(),revision=revision+1 where id=p.id; insert into public.model_annotation_event(annotation_package_id,clinic_id,event_type,actor_platform_user_id,revision) values(p.id,p.clinic_id,'finalized',c.actor_id,p.revision+1); return query select p.revision+1,true; end; $$;
revoke all on function graftvision_private.require_model_annotation_package(uuid,uuid,uuid),graftvision_private.create_model_annotation_package(uuid,uuid,uuid,integer,uuid),graftvision_private.save_model_annotation(uuid,uuid,uuid,text,text,jsonb,integer,uuid),graftvision_private.finalize_model_annotation_package(uuid,uuid,uuid,integer,uuid) from public,anon,authenticated;
