-- MODEL-001B2b2d: typed closed-region save.
create function graftvision_private.save_model_region(p_session_id uuid,p_provider_identity_id uuid,p_annotation_package_id uuid,p_region_code text,p_points jsonb,p_closed boolean,p_expected_package_revision integer,p_expected_pointer_revision integer,p_idempotency_key uuid)
returns table(region_version_id uuid,package_revision integer,pointer_revision integer,is_new boolean)
language plpgsql security definer set search_path='' as $$ declare p public.model_annotation_package%rowtype; m public.scalp_model_package%rowtype; c record; q public.model_annotation_region_current%rowtype; e public.model_annotation_idempotency%rowtype; v uuid; h text; n integer; hp boolean:=false; begin
 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation saves.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
select * into strict p from public.model_annotation_package where id=p_annotation_package_id for update; select * into strict m from public.scalp_model_package where id=p.model_package_id; select * into strict c from graftvision_private.require_scan_capture_context(p_session_id,p_provider_identity_id,m.scan_session_id);
 if p.package_state<>'draft' or p.clinic_id<>m.clinic_id or p.patient_id<>m.patient_id or p.consultation_id<>m.consultation_id or p.reconstruction_output_manifest_id<>m.reconstruction_output_manifest_id or p.model_artifact_id<>m.reconstruction_artifact_id or p.geometry_revision<>m.geometry_revision or p.normalization_version<>'graftvision-model-normalization-v1' or not graftvision_private.is_assigned_verified_doctor(p_session_id,p_provider_identity_id,p.consultation_id,'CONSULT-PERM-001') then raise exception using errcode='42501',message='MODEL_REGION_DENIED'; end if;
 if p.revision<>p_expected_package_revision or p_region_code not in ('frontal_recipient_region','mid_scalp_region','crown_region','left_temporal_region','right_temporal_region','donor_rear_region','donor_left_region','donor_right_region','exclusion_region') or not p_closed or jsonb_typeof(p_points)<>'array' then raise exception using errcode='22023',message='MODEL_REGION_INVALID'; end if; n:=jsonb_array_length(p_points);
 if n<4 or n>128 or exists(select 1 from jsonb_array_elements(p_points) x where jsonb_typeof(x)<>'object' or x->>'id' !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' or x->>'order_index' !~ '^(0|[1-9][0-9]*)$' or x->>'x' !~ '^-?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)$' or x->>'y' !~ '^-?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)$' or x->>'z' !~ '^-?(?:[0-9]+(?:\.[0-9]+)?|\.[0-9]+)$' or (x->>'x')::numeric not between -2 and 2 or (x->>'y')::numeric not between -2 and 2 or (x->>'z')::numeric not between -2 and 2) or (select count(distinct x->>'id') from jsonb_array_elements(p_points) x)<>n or (select count(distinct (x->>'order_index')::integer) from jsonb_array_elements(p_points) x)<>n or (select min((x->>'order_index')::integer) from jsonb_array_elements(p_points) x)<>0 or (select max((x->>'order_index')::integer) from jsonb_array_elements(p_points) x)<>n-1 or (p_points->0->>'x'=p_points->(n-1)->>'x' and p_points->0->>'y'=p_points->(n-1)->>'y' and p_points->0->>'z'=p_points->(n-1)->>'z') then raise exception using errcode='22023',message='MODEL_REGION_INVALID'; end if;
 h:=encode(extensions.digest(concat_ws(':',p_annotation_package_id,p_region_code,p_points::text,p_expected_package_revision,p_expected_pointer_revision),'sha256'),'hex'); select * into e from public.model_annotation_idempotency where clinic_id=p.clinic_id and actor_platform_user_id=c.actor_id and request_family='region' and idempotency_key=p_idempotency_key; if found then if e.payload_hash<>h then raise exception using errcode='40001',message='MODEL_REGION_IDEMPOTENCY_MISMATCH'; end if; return query select e.result_resource_id,e.result_revision,e.result_revision,false; return; end if;
 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation saves.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
select * into q from public.model_annotation_region_current where annotation_package_id=p.id and region_code=p_region_code for update; hp:=found; if hp and q.revision<>p_expected_pointer_revision then raise exception using errcode='40001',message='MODEL_REGION_POINTER_CONFLICT'; end if; if not hp and p_expected_pointer_revision<>0 then raise exception using errcode='40001',message='MODEL_REGION_POINTER_CONFLICT'; end if;
 perform set_config('graftvision.scan_controlled','on',true); insert into public.model_annotation_region_version(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,region_code,boundary_points,closed,revision,supersedes_region_id,created_by) values(p.id,p.clinic_id,p.patient_id,p.consultation_id,p.model_package_id,p.reconstruction_output_manifest_id,p.model_artifact_id,p.geometry_revision,p_region_code,p_points,true,p.revision+1,case when hp then q.current_version_id else null end,c.actor_id) returning id into v; insert into public.model_annotation_region_current(annotation_package_id,clinic_id,patient_id,consultation_id,model_package_id,reconstruction_output_manifest_id,model_artifact_id,geometry_revision,normalization_version,region_code,current_version_id,prior_version_id,revision,updated_by) values(p.id,p.clinic_id,p.patient_id,p.consultation_id,p.model_package_id,p.reconstruction_output_manifest_id,p.model_artifact_id,p.geometry_revision,p.normalization_version,p_region_code,v,case when hp then q.current_version_id else null end,1,c.actor_id) 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation saves.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
on conflict(annotation_package_id,region_code) do update set current_version_id=excluded.current_version_id,prior_version_id=model_annotation_region_current.current_version_id,revision=model_annotation_region_current.revision+1,updated_at=clock_timestamp(),updated_by=excluded.updated_by returning revision into pointer_revision; 
-- graftvision:dangerous-sql-approved task=MODEL-001
-- graftvision:dangerous-sql-reason Controlled row locks and revision updates serialize immutable Doctor annotation saves.
-- graftvision:corrective-plan Forward-fix through an additive migration; append-only annotation versions, pointers, events, and audit history remain preserved.
update public.model_annotation_package set revision=revision+1 where id=p.id returning revision into package_revision; insert into public.model_annotation_event(annotation_package_id,clinic_id,event_type,actor_platform_user_id,annotation_reference_id,annotation_code,revision) values(p.id,p.clinic_id,'region_saved',c.actor_id,v,p_region_code,package_revision); insert into public.audit_event(audit_scope,clinic_id,actor_platform_user_id,actor_type,action,resource_type,resource_id,outcome,request_id,source_application,metadata) values('clinic',p.clinic_id,c.actor_id,'user','model.region_saved','consultation',p.consultation_id,'success',p_idempotency_key,'web',jsonb_build_object('annotation_package_id',p.id,'model_package_id',p.model_package_id,'annotation_kind','region','annotation_code',p_region_code,'revision',package_revision,'package_state','draft','geometry_revision',p.geometry_revision)); insert into public.model_annotation_idempotency(clinic_id,actor_platform_user_id,request_family,idempotency_key,payload_hash,result_resource_id,result_status,result_revision) values(p.clinic_id,c.actor_id,'region',p_idempotency_key,h,v,'created',package_revision); return query select v,package_revision,pointer_revision,true; end; $$;
revoke all on function graftvision_private.save_model_region(uuid,uuid,uuid,text,jsonb,boolean,integer,integer,uuid) from public,anon,authenticated;
