-- MODEL-001B2b1: authoritative current pointers over immutable annotation versions.
create unique index model_annotation_landmark_version_binding_unique on public.model_annotation_landmark_version (id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, landmark_code);
create unique index model_annotation_curve_version_binding_unique on public.model_annotation_curve_version (id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, curve_code);
create unique index model_annotation_region_version_binding_unique on public.model_annotation_region_version (id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, region_code);

create table public.model_annotation_landmark_current (
  annotation_package_id uuid not null, clinic_id uuid not null, patient_id uuid not null, consultation_id uuid not null, model_package_id uuid not null, reconstruction_output_manifest_id uuid not null, model_artifact_id uuid not null, geometry_revision integer not null check (geometry_revision > 0), normalization_version text not null check (normalization_version = 'graftvision-model-normalization-v1'), landmark_code text not null check (landmark_code in ('glabella_reference','frontal_midline_reference','left_temporal_reference','right_temporal_reference','crown_center_reference','left_occipital_reference','right_occipital_reference','donor_center_reference','custom_technical_reference')), current_version_id uuid not null, prior_version_id uuid, revision integer not null default 1 check (revision > 0), updated_at timestamptz not null default clock_timestamp(), updated_by uuid not null references public.platform_user(id),
  primary key (annotation_package_id, landmark_code), check (prior_version_id is null or prior_version_id <> current_version_id),
  foreign key (current_version_id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, landmark_code) references public.model_annotation_landmark_version(id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, landmark_code)
);

create table public.model_annotation_curve_current (
  annotation_package_id uuid not null, clinic_id uuid not null, patient_id uuid not null, consultation_id uuid not null, model_package_id uuid not null, reconstruction_output_manifest_id uuid not null, model_artifact_id uuid not null, geometry_revision integer not null check (geometry_revision > 0), normalization_version text not null check (normalization_version = 'graftvision-model-normalization-v1'), curve_code text not null check (curve_code in ('current_hairline','proposed_hairline','frontal_boundary','left_temporal_boundary','right_temporal_boundary','donor_upper_boundary','donor_lower_boundary','donor_left_boundary','donor_right_boundary','crown_boundary')), current_version_id uuid not null, prior_version_id uuid, revision integer not null default 1 check (revision > 0), updated_at timestamptz not null default clock_timestamp(), updated_by uuid not null references public.platform_user(id),
  primary key (annotation_package_id, curve_code), check (prior_version_id is null or prior_version_id <> current_version_id),
  foreign key (current_version_id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, curve_code) references public.model_annotation_curve_version(id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, curve_code)
);

create table public.model_annotation_region_current (
  annotation_package_id uuid not null, clinic_id uuid not null, patient_id uuid not null, consultation_id uuid not null, model_package_id uuid not null, reconstruction_output_manifest_id uuid not null, model_artifact_id uuid not null, geometry_revision integer not null check (geometry_revision > 0), normalization_version text not null check (normalization_version = 'graftvision-model-normalization-v1'), region_code text not null check (region_code in ('frontal_recipient_region','mid_scalp_region','crown_region','left_temporal_region','right_temporal_region','donor_rear_region','donor_left_region','donor_right_region','exclusion_region')), current_version_id uuid not null, prior_version_id uuid, revision integer not null default 1 check (revision > 0), updated_at timestamptz not null default clock_timestamp(), updated_by uuid not null references public.platform_user(id),
  primary key (annotation_package_id, region_code), check (prior_version_id is null or prior_version_id <> current_version_id),
  foreign key (current_version_id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, region_code) references public.model_annotation_region_version(id, annotation_package_id, clinic_id, patient_id, consultation_id, model_package_id, reconstruction_output_manifest_id, model_artifact_id, geometry_revision, region_code)
);

alter table public.model_annotation_landmark_current enable row level security; alter table public.model_annotation_landmark_current force row level security;
alter table public.model_annotation_curve_current enable row level security; alter table public.model_annotation_curve_current force row level security;
alter table public.model_annotation_region_current enable row level security; alter table public.model_annotation_region_current force row level security;
revoke all on public.model_annotation_landmark_current, public.model_annotation_curve_current, public.model_annotation_region_current from public, anon, authenticated;
create trigger model_annotation_landmark_current_controlled before insert or update or delete on public.model_annotation_landmark_current for each row execute function graftvision_private.enforce_controlled_scan_mutation();
create trigger model_annotation_curve_current_controlled before insert or update or delete on public.model_annotation_curve_current for each row execute function graftvision_private.enforce_controlled_scan_mutation();
create trigger model_annotation_region_current_controlled before insert or update or delete on public.model_annotation_region_current for each row execute function graftvision_private.enforce_controlled_scan_mutation();
